# Generated by Django 4.1.5 on 2023-02-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_icon', models.CharField(max_length=50)),
                ('feature_title', models.CharField(max_length=50)),
                ('feature_desc', models.TextField()),
            ],
        ),
    ]
