# Generated by Django 4.1.5 on 2023-02-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_desc', models.TextField()),
                ('employ_name', models.CharField(max_length=20)),
                ('employ_post', models.CharField(max_length=50)),
            ],
        ),
    ]
