# Generated by Django 4.1.5 on 2023-02-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='services',
        ),
    ]
